spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9093
      bindings:
        consumer:
          destination: demoMicroservice
          contentType: application/json
        producer:
          destination: demoMicroservice
          contentType: application/json
server:
  port: 8091
          
          
            
